### ISSUE TITLE
Is Streaming.h really a dependency for this library?

### ISSUE THREAD

**Issue by imsyf** [avandalen/VirtualDelay#1]
I was trying to delete both #include `<Arduino.h>` and `#include <Streaming.h>` line, and my code (simple blinking LED) still working. So, what's the point of including them?

**Comment by avandalen** [comment]
It was for testing with Serial output

From: imsyf 
Sent: Saturday, September 16, 2017 8:50 AM
To: avandalen/VirtualDelay 
Cc: Subscribed 
Subject: [avandalen/VirtualDelay] Is Streaming.h really a dependency for this library? (#1)

I was trying to delete both #include <Arduino.h> and #include <Streaming.h> line, and my code (simple blinking LED) still working. So, what's the point of including them?

**Comment by avandalen** [comment]
It is just needed for printing like this: Serial << "blabla";
