### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CodingSpiderFox** [avandalen/VirtualDelay#3]
Please add a license

**Comment by avandalen** [comment]
GNU General Public License at http://www.gnu.org/licenses

**Comment by CodingSpiderFox** [comment]
Thanks

**Comment by regcs** [comment]
Thanks for this nice library. 
I found contradictory statements: The GitHub page states that this library is under the MIT license, but the source code files all state GPL (as this issue). May both licenses be used?

I would like to use it, but the GPL license will conflict with other libraries I would like to use as well ...
